# Generated by Django 2.2.13 on 2021-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210417_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='../media/profile/1.jpg', null=True, upload_to='profile/'),
        ),
    ]
