# Generated by Django 2.2.13 on 2021-04-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210410_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
